metadata:
  labels:
    uther: test
spec:
  template:
    spec:
      containers:
        -
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: darwincredssecret
